name: Copy tokens to remote repo

on:
  pull_request:
    types:
      - closed

jobs:
  copy_tokens:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.FIGMAVARIABLES }}
          src_branch: main
          src_path: tokens/.
          dst_owner: aldunchev
          dst_repo_name: tailwind-figma-variables
          dst_branch: main
          dst_path: tokens/.
          commit_message: Copy css tokens
