name: Sync Figma variables to tokens
on:
  workflow_dispatch:
    inputs:
      file_key:
        description: 'The file key of the Figma file to be updated'
        required: true

jobs:
  sync-figma-to-tokens:
    runs-on: ubuntu-latest
    permissions:
      # Need to be able to create new branches and commits
      contents: write
      pull-requests: write
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'

      - name: Set NPM version
        run: npm install -g npm@9.5.1

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Sync variables in Figma file to tokens
        run: npm run sync-figma-to-tokens -- --output tokens
        env:
          FILE_KEY: ${{ github.event.inputs.file_key }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_ACTION_VARIABLES_SYNC_FIGMA_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update tokens from Figma
          title: Update tokens from Figma
          body: 'Update tokens from Figma from file: https://www.figma.com/file/${{ github.event.inputs.file_key }}'
          branch: update-tokens

  copy_tokens:
    runs-on: ubuntu-latest
    needs: [sync-figma-to-tokens]
    steps:
      - uses: andstor/copycat-action@v3.2.4
        with:
          personal_token: ${{ secrets.FIGMAVARIABLES }}
          src_branch: main
          src_path: tokens/.
          dst_owner: aldunchev
          dst_repo_name: FigmaVariablesTransform
          dst_branch: main
          dst_path: tokens/.
          commit_message: copy css tokens
